// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entity "wiliam.dev/product/entity"
import mock "github.com/stretchr/testify/mock"

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx
func (_m *UseCase) List(ctx context.Context) ([]*entity.Product, error) {
	ret := _m.Called(ctx)

	var r0 []*entity.Product
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
