// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: grpc/v1beta1/product_api.proto

package grpcv1beta1

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ListProductsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductsRequest) Reset()         { *m = ListProductsRequest{} }
func (m *ListProductsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductsRequest) ProtoMessage()    {}
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e3728d893b1880a, []int{0}
}
func (m *ListProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsRequest.Unmarshal(m, b)
}
func (m *ListProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsRequest.Marshal(b, m, deterministic)
}
func (m *ListProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsRequest.Merge(m, src)
}
func (m *ListProductsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductsRequest.Size(m)
}
func (m *ListProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsRequest proto.InternalMessageInfo

func (m *ListProductsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListProductsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListProductsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListProductsResponse struct {
	Products             []*CreateProductResponse `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken        string                   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListProductsResponse) Reset()         { *m = ListProductsResponse{} }
func (m *ListProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductsResponse) ProtoMessage()    {}
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e3728d893b1880a, []int{1}
}
func (m *ListProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsResponse.Unmarshal(m, b)
}
func (m *ListProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsResponse.Marshal(b, m, deterministic)
}
func (m *ListProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsResponse.Merge(m, src)
}
func (m *ListProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductsResponse.Size(m)
}
func (m *ListProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsResponse proto.InternalMessageInfo

func (m *ListProductsResponse) GetProducts() []*CreateProductResponse {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *ListProductsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type CreateProductRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PriceInCents         int32    `protobuf:"varint,3,opt,name=price_in_cents,json=priceInCents,proto3" json:"price_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e3728d893b1880a, []int{2}
}
func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateProductRequest) GetPriceInCents() int32 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

type CreateProductResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceInCents         int32    `protobuf:"varint,4,opt,name=price_in_cents,json=priceInCents,proto3" json:"price_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e3728d893b1880a, []int{3}
}
func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

func (m *CreateProductResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateProductResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateProductResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateProductResponse) GetPriceInCents() int32 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

func init() {
	proto.RegisterType((*ListProductsRequest)(nil), "grpc.v1beta1.ListProductsRequest")
	proto.RegisterType((*ListProductsResponse)(nil), "grpc.v1beta1.ListProductsResponse")
	proto.RegisterType((*CreateProductRequest)(nil), "grpc.v1beta1.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "grpc.v1beta1.CreateProductResponse")
}

func init() { proto.RegisterFile("grpc/v1beta1/product_api.proto", fileDescriptor_8e3728d893b1880a) }

var fileDescriptor_8e3728d893b1880a = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0x9d, 0x2f, 0xfd, 0xda, 0x9b, 0xb4, 0x45, 0x43, 0x50, 0x43, 0x08, 0x25, 0x98, 0x1f,
	0x05, 0x16, 0xb1, 0x52, 0x56, 0xb0, 0xa9, 0x9a, 0x2e, 0xaa, 0x48, 0x2c, 0x2c, 0x83, 0xaa, 0xaa,
	0x42, 0xb2, 0x26, 0xf6, 0xc5, 0x0c, 0x84, 0x99, 0xc1, 0x33, 0x89, 0x50, 0x01, 0x21, 0x81, 0x78,
	0x02, 0x24, 0x1e, 0x00, 0x76, 0x3c, 0x0a, 0x5b, 0x5e, 0x80, 0x05, 0x0f, 0x82, 0xc6, 0xe3, 0x44,
	0x36, 0x94, 0x8a, 0xe5, 0xdc, 0x73, 0xee, 0xdc, 0x73, 0xee, 0x9c, 0x81, 0xed, 0x34, 0x93, 0xb1,
	0x3f, 0x1f, 0x4e, 0x50, 0xd3, 0xa1, 0x2f, 0x33, 0x91, 0xcc, 0x62, 0x1d, 0x51, 0xc9, 0x06, 0x32,
	0x13, 0x5a, 0x90, 0xa6, 0xc1, 0x07, 0x05, 0xde, 0xe9, 0xa6, 0x42, 0xa4, 0x53, 0xf4, 0xa9, 0x64,
	0x3e, 0xe5, 0x5c, 0x68, 0xaa, 0x99, 0xe0, 0xca, 0x72, 0x3b, 0x57, 0x4a, 0xe8, 0x63, 0x86, 0xd3,
	0x24, 0x9a, 0xe0, 0x13, 0x3a, 0x67, 0x22, 0xb3, 0x04, 0xef, 0x29, 0x9c, 0xbf, 0xcf, 0x94, 0x0e,
	0xec, 0x14, 0x15, 0xe2, 0x8b, 0x19, 0x2a, 0x4d, 0xb6, 0xe0, 0xff, 0x99, 0xc2, 0x2c, 0x62, 0x49,
	0xdb, 0xe9, 0x39, 0xfd, 0xb5, 0x70, 0xc5, 0x1c, 0xc7, 0x09, 0xb9, 0x04, 0x6b, 0x92, 0xa6, 0x18,
	0x29, 0x76, 0x82, 0x6d, 0xb7, 0xe7, 0xf4, 0xeb, 0xe1, 0xaa, 0x29, 0x3c, 0x60, 0x27, 0x48, 0x2e,
	0x03, 0xe4, 0xa0, 0x16, 0xcf, 0x90, 0xb7, 0x6b, 0x79, 0x63, 0x4e, 0x7f, 0x68, 0x0a, 0xde, 0x5b,
	0x68, 0x55, 0x67, 0x29, 0x29, 0xb8, 0x42, 0xb2, 0x0b, 0xab, 0x85, 0x4b, 0xd5, 0x76, 0x7a, 0xb5,
	0x7e, 0x63, 0xe7, 0xda, 0xa0, 0xec, 0x71, 0xb0, 0x9f, 0x21, 0xd5, 0x58, 0xf4, 0x2d, 0xda, 0xc2,
	0x65, 0x13, 0xb9, 0x09, 0x9b, 0x1c, 0x5f, 0xea, 0xa8, 0x34, 0xdc, 0xcd, 0x87, 0xaf, 0x9b, 0x72,
	0xb0, 0x14, 0xf0, 0xde, 0x81, 0xd6, 0x6f, 0x77, 0x59, 0xbb, 0x17, 0xa1, 0xae, 0x99, 0x9e, 0xa2,
	0x35, 0x3b, 0xaa, 0xfd, 0xd8, 0x73, 0x43, 0x5b, 0x21, 0x37, 0xa0, 0x91, 0xa0, 0x8a, 0x33, 0x26,
	0xcd, 0x5e, 0xed, 0xbd, 0x96, 0x50, 0xae, 0x93, 0x5b, 0xb0, 0x21, 0x33, 0x16, 0x63, 0xc4, 0x78,
	0x14, 0x23, 0xd7, 0x2a, 0xb7, 0x5f, 0xb7, 0xcc, 0x66, 0x0e, 0x8d, 0xf9, 0xbe, 0x01, 0xbc, 0x0f,
	0x0e, 0x5c, 0x38, 0xd5, 0x11, 0xd9, 0x00, 0x77, 0xb9, 0x70, 0x97, 0x25, 0xa4, 0xb5, 0x90, 0x65,
	0xdd, 0x14, 0x8a, 0x7a, 0x55, 0x45, 0x76, 0xcd, 0x15, 0x31, 0xd7, 0xff, 0x10, 0xf3, 0x5f, 0xfe,
	0x52, 0x15, 0x1d, 0x3b, 0x5f, 0x5c, 0x80, 0x42, 0xc1, 0x5e, 0x30, 0x26, 0x9f, 0x1c, 0x68, 0x96,
	0x9f, 0x87, 0x5c, 0xad, 0x3e, 0xc2, 0x29, 0x31, 0xe9, 0x78, 0x67, 0x51, 0xac, 0x29, 0x6f, 0xf7,
	0xdd, 0xf7, 0x9f, 0x1f, 0xdd, 0xbb, 0x64, 0xcb, 0x9f, 0x0f, 0xfd, 0x98, 0x6a, 0x3a, 0x15, 0x29,
	0xe3, 0xe9, 0x22, 0xd8, 0xea, 0x78, 0x9b, 0x74, 0x0d, 0x64, 0x02, 0xa6, 0xfc, 0x57, 0x45, 0xec,
	0xde, 0x2c, 0x71, 0xf2, 0x1a, 0xd6, 0x2b, 0xeb, 0x22, 0xde, 0x99, 0xe9, 0xb0, 0xca, 0xfe, 0x25,
	0x41, 0x9e, 0x97, 0x4b, 0xeb, 0x7a, 0x7f, 0x93, 0x76, 0xcf, 0xb9, 0x3d, 0x3a, 0x84, 0x73, 0xb1,
	0x78, 0x5e, 0xb9, 0x6d, 0xb4, 0xb9, 0x58, 0x9b, 0x64, 0x81, 0xf9, 0x45, 0x81, 0x73, 0xdc, 0x30,
	0x84, 0x02, 0xff, 0xec, 0xd6, 0x0e, 0x8e, 0x8e, 0xbe, 0xba, 0xcd, 0x03, 0xd3, 0x74, 0x38, 0x1c,
	0x99, 0xe2, 0x37, 0x7b, 0x7c, 0x54, 0x1c, 0x27, 0x2b, 0xf9, 0xff, 0xbb, 0xf3, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0xa4, 0x85, 0x8d, 0xc8, 0xee, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductAPIClient is the client API for ProductAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductAPIClient interface {
	// ListProduct.
	// This enables the following two alternative HTTP JSON to RPC mappings:
	//
	// HTTP | gRPC
	// -----|-----
	// `GET /v1/cataloging/products` | `ListProducts()`
	// `GET /v1/users/me/products` | `ListProducts(user_id: "me")
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	// CreateProduct.
	// This enables the following alternative HTTP JSON to RPC mappings:
	//
	// HTTP | gRPC
	// -----|-----
	// `POST /v1/cataloging/products` | `CreateProducts()`
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
}

type productAPIClient struct {
	cc *grpc.ClientConn
}

func NewProductAPIClient(cc *grpc.ClientConn) ProductAPIClient {
	return &productAPIClient{cc}
}

func (c *productAPIClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, "/grpc.v1beta1.ProductAPI/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAPIClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, "/grpc.v1beta1.ProductAPI/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductAPIServer is the server API for ProductAPI service.
type ProductAPIServer interface {
	// ListProduct.
	// This enables the following two alternative HTTP JSON to RPC mappings:
	//
	// HTTP | gRPC
	// -----|-----
	// `GET /v1/cataloging/products` | `ListProducts()`
	// `GET /v1/users/me/products` | `ListProducts(user_id: "me")
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	// CreateProduct.
	// This enables the following alternative HTTP JSON to RPC mappings:
	//
	// HTTP | gRPC
	// -----|-----
	// `POST /v1/cataloging/products` | `CreateProducts()`
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
}

// UnimplementedProductAPIServer can be embedded to have forward compatible implementations.
type UnimplementedProductAPIServer struct {
}

func (*UnimplementedProductAPIServer) ListProducts(ctx context.Context, req *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (*UnimplementedProductAPIServer) CreateProduct(ctx context.Context, req *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}

func RegisterProductAPIServer(s *grpc.Server, srv ProductAPIServer) {
	s.RegisterService(&_ProductAPI_serviceDesc, srv)
}

func _ProductAPI_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAPIServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.v1beta1.ProductAPI/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAPIServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAPI_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAPIServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.v1beta1.ProductAPI/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAPIServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.v1beta1.ProductAPI",
	HandlerType: (*ProductAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProducts",
			Handler:    _ProductAPI_ListProducts_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _ProductAPI_CreateProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/v1beta1/product_api.proto",
}
