// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: promotion/grpc/v1alpha1/discount.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Discount message.
type Discount struct {
	Pct                  float32  `protobuf:"fixed32,1,opt,name=pct,proto3" json:"pct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61995db67a93524, []int{0}
}
func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetPct() float32 {
	if m != nil {
		return m.Pct
	}
	return 0
}

func init() {
	proto.RegisterType((*Discount)(nil), "promotion.grpc.v1alpha1.Discount")
}

func init() {
	proto.RegisterFile("promotion/grpc/v1alpha1/discount.proto", fileDescriptor_d61995db67a93524)
}

var fileDescriptor_d61995db67a93524 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0x28, 0xca, 0xcf,
	0xcd, 0x2f, 0xc9, 0xcc, 0xcf, 0xd3, 0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0x33, 0x4c, 0xcc, 0x29,
	0xc8, 0x48, 0x34, 0xd4, 0x4f, 0xc9, 0x2c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x87, 0xab, 0xd3, 0x03, 0xa9, 0xd3, 0x83, 0xa9, 0x53, 0x92, 0xe1, 0xe2,
	0x70, 0x81, 0x2a, 0x15, 0x12, 0xe0, 0x62, 0x2e, 0x48, 0x2e, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x0a, 0x02, 0x31, 0x9d, 0xb8, 0xa2, 0x38, 0x60, 0x2a, 0x93, 0xd8, 0xc0, 0x26, 0x19, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xd7, 0xc2, 0xa6, 0x19, 0x73, 0x00, 0x00, 0x00,
}
