// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: promotion/grpc/v1alpha1/promotion_api.proto

package v1alpha1

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	date "google.golang.org/genproto/googleapis/type/date"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequestResponse struct {
	UserId               string     `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DateOfBirth          *date.Date `protobuf:"bytes,2,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateUserRequestResponse) Reset()         { *m = CreateUserRequestResponse{} }
func (m *CreateUserRequestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequestResponse) ProtoMessage()    {}
func (*CreateUserRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f55e80d4b4883fac, []int{0}
}
func (m *CreateUserRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequestResponse.Unmarshal(m, b)
}
func (m *CreateUserRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequestResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequestResponse.Merge(m, src)
}
func (m *CreateUserRequestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequestResponse.Size(m)
}
func (m *CreateUserRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequestResponse proto.InternalMessageInfo

func (m *CreateUserRequestResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateUserRequestResponse) GetDateOfBirth() *date.Date {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

type RetrievePromotionRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrievePromotionRequest) Reset()         { *m = RetrievePromotionRequest{} }
func (m *RetrievePromotionRequest) String() string { return proto.CompactTextString(m) }
func (*RetrievePromotionRequest) ProtoMessage()    {}
func (*RetrievePromotionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f55e80d4b4883fac, []int{1}
}
func (m *RetrievePromotionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievePromotionRequest.Unmarshal(m, b)
}
func (m *RetrievePromotionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievePromotionRequest.Marshal(b, m, deterministic)
}
func (m *RetrievePromotionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievePromotionRequest.Merge(m, src)
}
func (m *RetrievePromotionRequest) XXX_Size() int {
	return xxx_messageInfo_RetrievePromotionRequest.Size(m)
}
func (m *RetrievePromotionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievePromotionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievePromotionRequest proto.InternalMessageInfo

func (m *RetrievePromotionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RetrievePromotionRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type RetrievePromotionResponse struct {
	Discounts            []*Discount `protobuf:"bytes,1,rep,name=discounts,proto3" json:"discounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RetrievePromotionResponse) Reset()         { *m = RetrievePromotionResponse{} }
func (m *RetrievePromotionResponse) String() string { return proto.CompactTextString(m) }
func (*RetrievePromotionResponse) ProtoMessage()    {}
func (*RetrievePromotionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f55e80d4b4883fac, []int{2}
}
func (m *RetrievePromotionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievePromotionResponse.Unmarshal(m, b)
}
func (m *RetrievePromotionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievePromotionResponse.Marshal(b, m, deterministic)
}
func (m *RetrievePromotionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievePromotionResponse.Merge(m, src)
}
func (m *RetrievePromotionResponse) XXX_Size() int {
	return xxx_messageInfo_RetrievePromotionResponse.Size(m)
}
func (m *RetrievePromotionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievePromotionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievePromotionResponse proto.InternalMessageInfo

func (m *RetrievePromotionResponse) GetDiscounts() []*Discount {
	if m != nil {
		return m.Discounts
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequestResponse)(nil), "promotion.grpc.v1alpha1.CreateUserRequestResponse")
	proto.RegisterType((*RetrievePromotionRequest)(nil), "promotion.grpc.v1alpha1.RetrievePromotionRequest")
	proto.RegisterType((*RetrievePromotionResponse)(nil), "promotion.grpc.v1alpha1.RetrievePromotionResponse")
}

func init() {
	proto.RegisterFile("promotion/grpc/v1alpha1/promotion_api.proto", fileDescriptor_f55e80d4b4883fac)
}

var fileDescriptor_f55e80d4b4883fac = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xd7, 0x09, 0xd3, 0xbd, 0xd3, 0xc3, 0x72, 0x70, 0x5d, 0x41, 0x98, 0x3d, 0xc8, 0x40,
	0x48, 0x59, 0xc5, 0xb3, 0x38, 0x77, 0xd9, 0xc9, 0x11, 0xf0, 0x22, 0x42, 0xe9, 0xd6, 0x77, 0x5b,
	0x70, 0x2e, 0x31, 0x49, 0x07, 0x82, 0x47, 0x3f, 0xb8, 0x64, 0xfd, 0xb3, 0x83, 0xe6, 0xa0, 0xc7,
	0xbe, 0xf9, 0x3d, 0xcf, 0xf3, 0x3e, 0x4d, 0xe0, 0x5a, 0x2a, 0xf1, 0x26, 0x0c, 0x17, 0xdb, 0x68,
	0xa5, 0xe4, 0x22, 0xda, 0x8d, 0xd2, 0x8d, 0x5c, 0xa7, 0xa3, 0xa8, 0x9e, 0x27, 0xa9, 0xe4, 0x54,
	0x2a, 0x61, 0x04, 0xe9, 0xd5, 0x43, 0x6a, 0x61, 0x5a, 0xc1, 0xc1, 0xf9, 0x4a, 0x88, 0xd5, 0x06,
	0x23, 0xf3, 0x21, 0x31, 0xca, 0x52, 0x83, 0x85, 0x20, 0xb8, 0x72, 0xb9, 0x67, 0x5c, 0x2f, 0x44,
	0xbe, 0x35, 0x05, 0x17, 0xbe, 0x42, 0xff, 0x41, 0x61, 0x6a, 0xf0, 0x49, 0xa3, 0x62, 0xf8, 0x9e,
	0xa3, 0x36, 0x0c, 0xb5, 0x14, 0x5b, 0x8d, 0xa4, 0x07, 0xc7, 0xb9, 0x46, 0x95, 0xf0, 0xcc, 0xf7,
	0x06, 0xde, 0xb0, 0xcd, 0x5a, 0xf6, 0x73, 0x9a, 0x91, 0x5b, 0x38, 0xb3, 0x59, 0x89, 0x58, 0x26,
	0x73, 0xae, 0xcc, 0xda, 0x6f, 0x0e, 0xbc, 0x61, 0x27, 0xee, 0xd2, 0x62, 0x1b, 0x6a, 0xb7, 0xa1,
	0x93, 0xd4, 0x20, 0xeb, 0x58, 0xee, 0x71, 0x39, 0xb6, 0x54, 0xc8, 0xc0, 0x67, 0x68, 0x14, 0xc7,
	0x1d, 0xce, 0xaa, 0xf5, 0xca, 0x4c, 0x77, 0xd6, 0x05, 0x80, 0x54, 0x22, 0xcb, 0x17, 0xc6, 0x9e,
	0x35, 0xf7, 0x67, 0xed, 0x72, 0x32, 0xcd, 0xc2, 0x17, 0xe8, 0xff, 0xe2, 0x59, 0x16, 0xb8, 0x83,
	0x76, 0xd5, 0x57, 0xfb, 0xde, 0xe0, 0x68, 0xd8, 0x89, 0x2f, 0xa9, 0xe3, 0x57, 0xd2, 0x49, 0x49,
	0xb2, 0x83, 0x26, 0xfe, 0x6a, 0xc2, 0x69, 0x6d, 0x7b, 0x3f, 0x9b, 0x92, 0x4f, 0xe8, 0xfe, 0x88,
	0x23, 0x23, 0xa7, 0xa7, 0xab, 0x6e, 0x10, 0xff, 0x45, 0x52, 0xb4, 0x09, 0x1b, 0x64, 0x07, 0x70,
	0xb8, 0x2d, 0xe2, 0xf6, 0x70, 0x5e, 0x69, 0xf0, 0x0f, 0x4d, 0xd8, 0x18, 0xc3, 0xf3, 0x49, 0xc5,
	0xcd, 0x5b, 0xfb, 0x87, 0x73, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xae, 0x56, 0x7c, 0x6b, 0xc0,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PromotionAPIClient is the client API for PromotionAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PromotionAPIClient interface {
	// RetrievePromotion.
	// This retrieve all discounts by product and user IDs.
	RetrievePromotion(ctx context.Context, in *RetrievePromotionRequest, opts ...grpc.CallOption) (*RetrievePromotionResponse, error)
	//CreateUser
	// This is used to populate user data store.
	CreateUser(ctx context.Context, in *CreateUserRequestResponse, opts ...grpc.CallOption) (*CreateUserRequestResponse, error)
}

type promotionAPIClient struct {
	cc *grpc.ClientConn
}

func NewPromotionAPIClient(cc *grpc.ClientConn) PromotionAPIClient {
	return &promotionAPIClient{cc}
}

func (c *promotionAPIClient) RetrievePromotion(ctx context.Context, in *RetrievePromotionRequest, opts ...grpc.CallOption) (*RetrievePromotionResponse, error) {
	out := new(RetrievePromotionResponse)
	err := c.cc.Invoke(ctx, "/promotion.grpc.v1alpha1.PromotionAPI/RetrievePromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionAPIClient) CreateUser(ctx context.Context, in *CreateUserRequestResponse, opts ...grpc.CallOption) (*CreateUserRequestResponse, error) {
	out := new(CreateUserRequestResponse)
	err := c.cc.Invoke(ctx, "/promotion.grpc.v1alpha1.PromotionAPI/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionAPIServer is the server API for PromotionAPI service.
type PromotionAPIServer interface {
	// RetrievePromotion.
	// This retrieve all discounts by product and user IDs.
	RetrievePromotion(context.Context, *RetrievePromotionRequest) (*RetrievePromotionResponse, error)
	//CreateUser
	// This is used to populate user data store.
	CreateUser(context.Context, *CreateUserRequestResponse) (*CreateUserRequestResponse, error)
}

// UnimplementedPromotionAPIServer can be embedded to have forward compatible implementations.
type UnimplementedPromotionAPIServer struct {
}

func (*UnimplementedPromotionAPIServer) RetrievePromotion(ctx context.Context, req *RetrievePromotionRequest) (*RetrievePromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrievePromotion not implemented")
}
func (*UnimplementedPromotionAPIServer) CreateUser(ctx context.Context, req *CreateUserRequestResponse) (*CreateUserRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterPromotionAPIServer(s *grpc.Server, srv PromotionAPIServer) {
	s.RegisterService(&_PromotionAPI_serviceDesc, srv)
}

func _PromotionAPI_RetrievePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrievePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionAPIServer).RetrievePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promotion.grpc.v1alpha1.PromotionAPI/RetrievePromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionAPIServer).RetrievePromotion(ctx, req.(*RetrievePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionAPI_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequestResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionAPIServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promotion.grpc.v1alpha1.PromotionAPI/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionAPIServer).CreateUser(ctx, req.(*CreateUserRequestResponse))
	}
	return interceptor(ctx, in, info, handler)
}

var _PromotionAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "promotion.grpc.v1alpha1.PromotionAPI",
	HandlerType: (*PromotionAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrievePromotion",
			Handler:    _PromotionAPI_RetrievePromotion_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _PromotionAPI_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promotion/grpc/v1alpha1/promotion_api.proto",
}
